name: Build and Release Application

on:
  push:
    tags:
      - v*.*.*

jobs:
  build_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Setup node v17
        uses: actions/setup-node@v1
        with:
          node-version: 17
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Cache opencv-bindings build and bin
        uses: actions/cache@v2
        with:
          path: |
            opencv-bindings/build
            opencv-bindings/bin
          key: ${{ runner.os }}-opencv-bindings
      - name: Build app
        run: OPENCV_ROOT=./prebuilt-opencv/ npm run package
      - name: Compress app
        uses: papeloto/action-zip@v1
        with:
          files: out/fps-checker-win32-x64
          recursive: true
          dest: out/fps-checker.zip
      - name: Upload app
        uses: actions/upload-artifact@v3
        with:
          name: fps-checker
          path: out/fps-checker.zip

  release_app:
    runs-on: ubuntu-latest
    needs: [build_windows]
    steps:
      - name: Download app
        uses: actions/download-artifact@v3
        with:
          name: fps-checker
      - name: Release app
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            fps-checker.zip

